version: '3.8'

services:
  app_texto:
    build: 
      context: .
      dockerfile: app_texto/Dockerfile
    container_name: app_texto
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  app_hora:
    build:
      context: .
      dockerfile: app_hora/Dockerfile
    container_name: app_hora
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
